declare module '*.module.css'
// declare module 'react-router-dom'
declare module 'localbase'
declare module '*.gif'
declare module 'react-csv'
declare module 'react-sp-people-picker'
declare module 'dompurify'
declare module 'react-html-parser'
declare module 'react-infinite-scroller'
declare module 'pdfjs-dist/build/pdf.worker.entry'
declare module 'sheetjs-style'
